# Generated by Django 4.2.1 on 2023-06-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwords'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
