# Generated by Django 4.2.1 on 2023-07-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordentry_delete_passwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='encryption_key',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='salt',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
