# Generated by Django 4.2.1 on 2023-07-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_id_customuser_auth_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auth_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
